# Generated by Django 5.2.5 on 2025-09-16 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('document_type', models.CharField(choices=[('pdf_import', 'PDF Importé'), ('grapesjs_project', 'Projet GrapesJS'), ('generated_offer', 'Offre Générée')], max_length=20, verbose_name='Type de document')),
                ('offer_structure', models.JSONField(blank=True, null=True, verbose_name="Structure de l'offre")),
                ('grapes_html', models.TextField(blank=True, verbose_name='HTML GrapesJS')),
                ('grapes_css', models.TextField(blank=True, verbose_name='CSS GrapesJS')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='documents/pdfs/', verbose_name='Fichier PDF')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='documents/thumbnails/', verbose_name='Miniature')),
                ('company_info', models.JSONField(default=dict, verbose_name='Informations entreprise')),
                ('assets', models.JSONField(default=list, verbose_name='Assets (images, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('file', models.FileField(upload_to='documents/assets/', verbose_name='Fichier')),
                ('file_type', models.CharField(max_length=50, verbose_name='Type de fichier')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Largeur')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Hauteur')),
                ('size_kb', models.FloatField(blank=True, null=True, verbose_name='Taille (KB)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_assets', to='api.document')),
            ],
            options={
                'verbose_name': 'Asset de document',
                'verbose_name_plural': 'Assets de documents',
            },
        ),
    ]
