# Generated by Django 5.2.5 on 2025-09-16 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_document_owner_folder_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du template')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('template_type', models.CharField(choices=[('travel_offer', 'Offre de voyage'), ('brochure', 'Brochure'), ('newsletter', 'Newsletter'), ('custom', 'Personnalisé')], default='custom', max_length=20, verbose_name='Type de template')),
                ('grapes_html', models.TextField(verbose_name='HTML GrapesJS')),
                ('grapes_css', models.TextField(verbose_name='CSS GrapesJS')),
                ('grapes_components', models.JSONField(default=dict, verbose_name='Composants GrapesJS')),
                ('grapes_styles', models.JSONField(default=list, verbose_name='Styles GrapesJS')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='templates/thumbnails/', verbose_name='Miniature')),
                ('is_default', models.BooleanField(default=False, verbose_name='Template par défaut')),
                ('is_public', models.BooleanField(default=False, verbose_name='Template public (partagé)')),
                ('color_scheme', models.JSONField(default=dict, verbose_name='Palette de couleurs')),
                ('fonts', models.JSONField(default=list, verbose_name='Polices utilisées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Template utilisateur',
                'verbose_name_plural': 'Templates utilisateurs',
                'ordering': ['-updated_at'],
                'unique_together': {('owner', 'name')},
            },
        ),
    ]
