# Generated by Django 5.2.5 on 2026-03-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_document_puck_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('pdf_import', 'PDF Importé'), ('grapesjs_project', 'Projet GrapesJS'), ('puck_project', 'Projet Puck'), ('generated_offer', 'Offre Générée')], max_length=20, verbose_name='Type de document'),
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
