# Generated by Django 5.2.5 on 2026-03-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_document_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='blocknote_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Données BlockNote Editor'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('pdf_import', 'PDF Importé'), ('grapesjs_project', 'Projet GrapesJS'), ('puck_project', 'Projet Puck'), ('blocknote', 'Document BlockNote'), ('generated_offer', 'Offre Générée')], max_length=20, verbose_name='Type de document'),
        ),
    ]
